queue_rules:
  - name: default
    conditions:
      - -draft # not a draft
      - base=main

pull_request_rules:
  - name: Automatic merge on approval and when when GitHub branch protection passes on main
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by<1"
      - -draft
      - base=main
      - label!=dependencies
    actions:
      queue:
        method: merge
        name: default
