pull_request_rules:
  - name: For dependabot, automatic merge on approval and when when GitHub branch protection passes on main
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=dependencies
    actions:
      merge:
        method: merge
        strict: false
   
pull_request_rules:
  - name: Automatic merge on approval and when when GitHub branch protection passes on main
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label!=dependencies
    actions:
      merge:
        method: merge
        strict: smart
